---

- name: Install python-software-properties
  apt:
    name: python-software-properties

- name: Install python-pycurl
  apt:
    name: python-pycurl

- name: Add jenkins apt-key
  apt_key:
    data: "{{ lookup('file', 'jenkins-ci.org.key') }}"

- name: Add Jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/

- name: Install Jenkins
  apt:
    name: jenkins

- name: Don't bind Jenkins to port 8080
  lineinfile:
    dest: /etc/default/jenkins
    line: HTTP_PORT=8080
    state: absent

- name: Bind Jenkins to port 8081
  lineinfile:
    dest: /etc/default/jenkins
    line: HTTP_PORT=8081
    insertbefore: ^JENKINS_ARGS=
