---

- name: Install rbenv dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev

- name: create user
  user:
    name: "{{ user }}"
    shell: /bin/bash

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
  become_user: "{{ user }}"

- name: install ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
  become_user: "{{ user }}"

- name: init rbenv in bashrc
  lineinfile:
    line: eval "$(rbenv init -)"
    dest: ~/.bashrc
    insertbefore: BOF
  become_user: "{{ user }}"

- name: add rbenv to PATH
  lineinfile:
    line: export PATH="$HOME/.rbenv/bin:$PATH"
    dest: ~/.bashrc
    insertbefore: BOF
  become_user: "{{ user }}"

- name: install ruby {{ ruby_version }}
  command: "{{ item }}"
  args:
    creates: ~/.rbenv/versions/{{ ruby_version }}
  become_user: "{{ user }}"
  with_items:
    - ~/.rbenv/bin/rbenv install {{ ruby_version }} -s
    - ~/.rbenv/bin/rbenv global {{ ruby_version }}
    - ~/.rbenv/shims/gem install bundler
