---

- name: install python psycopg2
  apt:
    name: python-psycopg2

- name: Create SonarQube postgresql user
  postgresql_user:
    name: sonarqube
    password: "{{ sonarqube_db_password }}"
  become: true
  become_user: postgres

- name: Create sonar postgresql database
  postgresql_db:
    name: sonarqube
    owner: sonarqube
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
  become: true
  become_user: postgres

- name: Add SonarQube repository
  apt_repository:
    repo: deb http://downloads.sourceforge.net/project/sonar-pkg/deb binary/

- name: Add SonarQube apt key
  apt_key:
    url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

- name: Install SonarQube
  apt:
    name: sonar
    allow_unauthenticated: yes # Couldn't find an apt key for SonarQube
    update_cache: yes

- name: Configure SonarQube database
  lineinfile:
    dest: /opt/sonar/conf/sonar.properties
    line: "{{ item }}"
  with_items:
    - sonar.jdbc.username=sonarqube
    - sonar.jdbc.password={{ sonarqube_db_password }}
    - sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube
  notify: restart sonarqube

- name: Configure SonarQube suburi
  lineinfile:
    dest: /opt/sonar/conf/sonar.properties
    line: sonar.web.context=/sonarqube
  notify: restart sonarqube
